"""One-shot Markdown health report built from the core analyses.

Deterministic for a given repository state: no timestamps and no absolute
local paths, so the output can be committed, diffed or pasted into an issue.
"""

from __future__ import annotations

from pathlib import Path

from . import __version__, core

SPARK = "▁▂▃▄▅▆▇█"
SINGLE_OWNER_PERCENT = 80.0
STRONG_COUPLING = 0.5


def sparkline(values: list[int]) -> str:
    peak = max(values) if values else 0
    if peak == 0:
        return SPARK[0] * len(values)
    return "".join(SPARK[round(v / peak * (len(SPARK) - 1))] for v in values)


def _cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _code(path: str) -> str:
    return f"`{_cell(path)}`"


def _n(count: int, noun: str) -> str:
    return f"{count} {noun}{'' if count == 1 else 's'}"


def _table(headers: list[str], rows: list[list[object]], align: str = "") -> list[str]:
    align = align or "l" * len(headers)
    marks = {"l": "---", "r": "--:", "c": ":-:"}
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(marks[a] for a in align) + "|",
    ]
    lines += ["| " + " | ".join(_cell(c) if not str(c).startswith("`") else str(c) for c in row) + " |"
              for row in rows]
    return lines


def attention_list(hot: dict, risk: dict, coupling: dict) -> list[dict]:
    """Files that combine churn with a knowledge or coupling risk.

    A file qualifies when it has at least HOTSPOT_MIN_COMMITS commits in the
    window and at least one reason: orphaned (inactive authors own most of
    it, weight 3: code nobody active understands is still being changed), a
    single owner holding >= 80% of its lines (weight 1) or a strong change
    coupling, degree >= 0.5 (weight 1). Ranked by total weight, then by
    commits in the window.
    """
    by_file = {row["file"]: row for row in risk.get("files", [])}
    partners: dict[str, list[tuple[str, float]]] = {}
    for pair in coupling.get("pairs", []):
        if pair["degree"] >= STRONG_COUPLING:
            partners.setdefault(pair["file_a"], []).append((pair["file_b"], pair["degree"]))
            partners.setdefault(pair["file_b"], []).append((pair["file_a"], pair["degree"]))
    out = []
    for row in hot.get("hotspots", []):
        if row["commits"] < core.HOTSPOT_MIN_COMMITS:
            continue
        f = row["file"]
        reasons = []
        score = 0
        owner = by_file.get(f)
        if owner and owner["orphaned"]:
            score += 3
            reasons.append(
                f"{owner['inactive_percent']:g}% of its lines belong to inactive authors "
                f"(main owner {owner['main_owner']}, last commit {owner['main_owner_last_commit']})"
            )
        elif owner and owner["main_owner_percent"] >= SINGLE_OWNER_PERCENT:
            score += 1
            reasons.append(f"single owner: {owner['main_owner']} wrote {owner['main_owner_percent']:g}% of it")
        if f in partners:
            score += 1
            reasons.append("changes together with " + ", ".join(
                f"{_code(p)} (degree {d:.2f})" for p, d in sorted(partners[f])))
        if reasons:
            out.append({"file": f, "commits": row["commits"], "hotspot": "hint" in row,
                        "score": score, "reasons": reasons})
    out.sort(key=lambda r: (-r["score"], -r["commits"], r["file"]))
    return out


def build_report(
    repo_path: str,
    since: str = "1 year ago",
    inactive_after: str = "6 months ago",
    top: int = 10,
    max_files: int = 200,
) -> str:
    """Return a Markdown health report for the repository (or scoped folder)."""
    top = core._positive_int("top", top, 10)
    summary = core.repo_summary(repo_path)
    hot = core.hotspots(repo_path, since=since, top=max(top, 50))
    coupling = core.change_coupling(repo_path, since=since, top=max(top, 50))
    bus = core.bus_factor(repo_path, top=top)
    risk = core.knowledge_risk(repo_path, inactive_after=inactive_after, top=max_files, max_files=max_files)

    name = Path(summary["repo_root"]).name
    scope = f" — scope `{summary['scope']}`" if summary["scope"] else ""
    last = summary["last_commit"]
    window = hot["since"] if not hot["since_date"] else f"{hot['since']} (since {hot['since_date']})"
    md: list[str] = [
        f"# Git health report: {name}{scope}",
        "",
        f"Generated by mcp-git-historian {__version__} at commit `{last['hash']}` ({last['date']}) "
        f"on branch `{summary['branch']}`. Churn and coupling window: {window}.",
        "",
        "## Summary",
        "",
        f"- **{_n(summary['total_commits'], 'commit')}** ({_n(summary['merge_commits'], 'merge')}) from "
        f"{summary['first_commit']['date']} to {last['date']}, by **{_n(summary['total_authors'], 'author')}** "
        "(mailmap-resolved, merges excluded).",
        f"- **Bus factor {bus['bus_factor']}**: the smallest number of authors who together made more "
        "than half of all authored commits.",
        f"- **{_n(len([h for h in hot['hotspots'] if 'hint' in h]), 'churn hotspot')}** among "
        f"{_n(hot['files_changed'], 'file')} changed in the window.",
        f"- **{_n(coupling['pairs_found'], 'coupled file pair')}** (>= {coupling['min_shared']} shared commits).",
        f"- **{_n(risk['orphaned_files'], 'orphaned file')}** of {risk['files_analyzed']} analysed "
        f"(inactive = no commit since {risk['inactive_after_date']}).",
        "",
    ]

    months = list(summary["activity_by_month"])
    counts = list(summary["activity_by_month"].values())
    peak_month = months[counts.index(max(counts))] if counts and max(counts) else None
    md += [
        "## Activity (authored commits per month)",
        "",
        "```text",
        f"{months[0]} {sparkline(counts)} {months[-1]}",
        "```",
        "",
        f"Peak: {max(counts)} commits in {peak_month}." if peak_month else "No commits in the last 12 months.",
        "",
    ]

    attention = attention_list(hot, risk, coupling)
    md += ["## What to look at first", ""]
    if attention:
        md.append("Files that change often **and** carry a knowledge or coupling risk:")
        md.append("")
        for i, item in enumerate(attention[:top], 1):
            tag = " (hotspot)" if item["hotspot"] else ""
            md.append(f"{i}. {_code(item['file'])}: {item['commits']} commits in the window{tag}; "
                      + "; ".join(item["reasons"]) + ".")
    else:
        md.append("No frequently changed file combines churn with a knowledge or coupling risk.")
    md.append("")

    md += ["## Churn hotspots", ""]
    rows = []
    for h in hot["hotspots"][:top]:
        renamed = f" (was {', '.join(h['renamed_from'])})" if h.get("renamed_from") else ""
        rows.append([_code(h["file"]) + _cell(renamed), h["commits"], f"+{h['lines_added']} / -{h['lines_deleted']}",
                     f"{h['churn_percentile']:g}", "yes" if "hint" in h else ""])
    md += _table(["File", "Commits", "Lines", "Percentile", "Hotspot"], rows, "lrrrc") if rows else ["No changes in the window."]
    md += ["", f"_Rule: {hot['hint_rule']}._", ""]

    md += ["## Change coupling", ""]
    if coupling["pairs"]:
        rows = [[_code(p["file_a"]), _code(p["file_b"]), p["shared_commits"], f"{p['degree']:.2f}", f"{p['jaccard']:.2f}"]
                for p in coupling["pairs"][:top]]
        md += _table(["File", "Changes with", "Shared", "Degree", "Jaccard"], rows, "llrrr")
    else:
        md.append(f"No pair of files shares {coupling['min_shared']} or more commits in the window.")
    md += ["", f"_{coupling['commits_analyzed']} commits analysed, {coupling['commits_skipped_large']} "
           f"skipped for touching more than {coupling['max_files_per_commit']} files._", ""]

    md += ["## Knowledge", "", "### Directories (by commits)", ""]
    rows = [[_code(d["directory"]), d["commits"], d["authors"], d["dominant_author"], f"{d['dominant_percent']:g}%",
             "yes" if d["knowledge_silo"] else ""] for d in bus["directories"]]
    md += _table(["Directory", "Commits", "Authors", "Dominant author", "Share", "Silo"], rows, "lrrlrc")
    md += ["", f"_Silo rule: {bus['silo_rule']}._", "", "### Orphaned files (by surviving lines)", ""]
    orphans = [f for f in risk["files"] if f["orphaned"]]
    if orphans:
        rows = [[_code(f["file"]), f["lines"], f["main_owner"], f["main_owner_last_commit"], f"{f['inactive_percent']:g}%"]
                for f in orphans[:top]]
        md += _table(["File", "Lines", "Main owner", "Owner's last commit", "Inactive share"], rows, "lrllr")
    else:
        md.append(f"None: every analysed file is mostly owned by someone active since {risk['inactive_after_date']}.")
    if risk["truncated"]:
        md += ["", f"_{risk['truncation_note']}._"]
    md += ["", "### Who owns the code", ""]
    rows = [[a["author"], "yes" if a["active"] else "no", a["last_commit"], f"{a['lines_percent']:g}%", a["files_as_main_owner"]]
            for a in risk["authors"][:top]]
    md += _table(["Author", "Active", "Last commit", "Lines owned", "Files as main owner"], rows, "lclrr")
    md += [
        "",
        "---",
        "",
        f"_Orphan rule: {risk['orphan_rule']}. Authors are .mailmap-resolved; merge commits are "
        "excluded from churn and authorship. Reproduce with "
        f"`mcp-git-historian report <repo> --since \"{since}\" --inactive-after \"{inactive_after}\"`._",
        "",
    ]
    return "\n".join(md)
